### ISSUE TITLE
Feature request: Implement settings to prevent using the webshell in Debug mode

### ISSUE THREAD

**Issue by gdalmau** [onrik/django-webshell#10]
Implement settings similar to https://github.com/djk2/django-admin-shell#settings to prevent using the webshell in debug mode (unless explicitly enabled)

**Comment by yeongbin-jo** [comment]
You can edit `urls.py` to add url routes to patterns only when not in debug mode.

```python
# project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # and more patterns...
]

if not settings.DEBUG:
    urlpatterns += [path('admin/webshell/', include('webshell.urls'))]
```

The same method can be applied to `settings.py` as well.

**Comment by gdalmau** [comment]
@yeongbin-jo Right! I will close the issue :)
