### ISSUE TITLE
urls.py deprecated warning

### ISSUE THREAD

**Issue by ignus2** [onrik/django-webshell#2]
Hi,

First of all great app!

I get this warning with django 1.9.5:

> ...\lib\site-packages\webshell\urls.py:5: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
>   url(r'^execute/$', execute_script_view, name='execute-script'),

Can it be fixed?

**Comment by onrik** [comment]
Fixed in 0.1.1
