### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by danielcandidos** [onrik/django-webshell#9]
It doesn't work in Django 3, with the error below:

![static_admin_error](https://user-images.githubusercontent.com/7028975/74684629-2a59b100-51ab-11ea-8d25-4f622a6feeea.png)

I opened a pull request by changing the use of "static_admin" to only "static" in the change_form.html: https://github.com/onrik/django-webshell/pull/8

**Comment by gdalmau** [comment]
@danielcandidos It can be closed I guess since it was fixed in #8

**Comment by djk2** [comment]
Fact. 
Thanks for info. 
I close.

**Comment by danielcandidos** [comment]
It's true. I'm closing it.
